version: '2'
services:
  load_balancer:
    image: dockercloud/haproxy
    links:
        - web
    ports:
        - "80:80"
        - "443:443"

  cache:
    image: redis

  database:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=secret
        - MYSQL_DATABASE=myapp

  web:
#    image: appkr/lep-docker
    build: .
    links:
        - database
        - cache
    volumes:
        - .:/var/www
        - ./storage/logs:/var/log
    environment:
        - APP_ENV=local
        - DB_DATABASE=myapp
        - DB_PASSWORD=secret
        - VIRTUAL_HOST=myapp.local
volumes:
  myvolume: {}